### ISSUE TITLE
Only CurrencyType?

### ISSUE THREAD

**Issue by danbroooks** [zfbrasil/doctrine-money-module#30]
Am I missing something here? Does this module not provide a MoneyType as a type for Doctrine?

**Comment by danbroooks** [comment]
I'm new to both this and the [mathiasverraes/money](https://github.com/mathiasverraes/money) project, looks like this [once was provided by that dependency](https://github.com/mathiasverraes/money/blob/708d8d53b2374e1f9686dceee4f9636df32f6d43/lib/Money/Doctrine2/MoneyType.php). But seems that this is no more?

**Comment by danizord** [comment]
Hey @danbroooks, I'm sorry for the long delay, I did not see your issue before.

> Am I missing something here? Does this module not provide a MoneyType as a type for Doctrine? 

Yes, it does, we provide a [PHP mapping file](https://github.com/zfbrasil/doctrine-money-module/blob/53d865e6e28a21dd04553a3c3c8f8ed50224d785/mapping/PHPDriver/orm/Money.Money.php) for Money.

> I'm new to both this and the mathiasverraes/money project, looks like this once was provided by that project. But seems that this is no more?

Yeah, that's why we created this module.
